language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
  - apt-get install libudev-dev

script:
  - ng build --prod

deploy:
  provider: script
  script: npx angular-cli-ghpages --cname=vault.mynano.ninja --no-silent --name="BitDesert" --email=admin@mynano.ninja --repo=https://GH_TOKEN@github.com/BitDesert/NinjaVault
  skip_cleanup: true
  on:
    branch: master
